### ISSUE TITLE
关于文章《Clash Verge系列使用最佳实践》的一些问题

### ISSUE THREAD

**Issue by YoloBird** [lainbo/osmosfeed#1]
大佬你好，我最近在折腾自己的clash的分流规则，在无意间发现了您的博客，这篇博文您叙述的非常详尽，我采用了的您的方案之后，感觉体验确实有了提升，但是我在clash的日志中发现了一个WARNING  ‘‘dial 代理模式 (match Match/) 198.18.0.1:13628(svchost.exe) --> 192.168.2.65:7680 error: dial tcp 192.168.2.65:7680: i/o timeout’’ ，由于我是一个小白，并不知道这个warning是什么含义，但他频繁出现，所以我来您的github发了这个issue。

我的分流规则是这样的：除了正常的网页、APP之外，我在分流规则最后添加了一个MATCH，就是说假如有域名在上面的规则全部没有匹配的情况下就会匹配这条规则，然后这条规则对应的是“黑/白名单模式”，也就是我决定这些规则到底是代理还是直连。希望我提供的分流规则能为您了解问题产生帮助。

来这里发issue实在是不好意思，因为我在博客中没有找到联系方式，所以只能出此下策，如果您能帮我看一下这个问题，就太感谢了。
![image](https://github.com/lainbo/osmosfeed/assets/112264701/6fbdc6b8-4094-4d53-ad46-8ce703db1a97)
![image](https://github.com/lainbo/osmosfeed/assets/112264701/a88995a1-4d84-4d7a-b1a8-79b2c119adcf)
![image](https://github.com/lainbo/osmosfeed/assets/112264701/0e1c817a-a20d-4b1e-acd4-c367a1d8f561)

**Comment by lainbo** [comment]
1. 我更倾向于这个是内核在处理内部流量时出现的一些问题，在[内核的仓库](https://github.com/MetaCubeX/mihomo)可以经常看见这种相关的issue
2. [svchost.exe](https://zh.wikipedia.org/wiki/Svchost.exe)是Windows里专门用来执行程序dll的前导程序，根据[这篇文章](https://malwaretips.com/blogs/svchost-exe-virus-removal/)所说，svchost.exe可能通常不会直接请求网络，如果你看到了大量的网络请求，可能遇到了文中所说的被恶意软件滥用或者遇到了木马程序，希望我猜的是错的，但是也希望你运行一下杀毒软件检查电脑
3. warning的含义无法猜测，根据日志所说，就是朝着一个ip发送了请求，但是或许是i或许是o出现了超时问题，导致超时的可能很多，没有办法从这一条日志分析出来
4. 如果不影响正常使用，你可以忽略所有的warning，因为他并不是一个错误，而更像是一个提醒

**Comment by YoloBird** [comment]
> 1. 我更倾向于这个是内核在处理内部流量时出现的一些问题，在[内核的仓库](https://github.com/MetaCubeX/mihomo)可以经常看见这种相关的issue
> 2. [svchost.exe](https://zh.wikipedia.org/wiki/Svchost.exe)是Windows里专门用来执行程序dll的前导程序，根据[这篇文章](https://malwaretips.com/blogs/svchost-exe-virus-removal/)所说，svchost.exe可能通常不会直接请求网络，如果你看到了大量的网络请求，可能遇到了文中所说的被恶意软件滥用或者遇到了木马程序，希望我猜的是错的，但是也希望你运行一下杀毒软件检查电脑
> 3. warning的含义无法猜测，根据日志所说，就是朝着一个ip发送了请求，但是或许是i或许是o出现了超时问题，导致超时的可能很多，没有办法从这一条日志分析出来
> 4. 如果不影响正常使用，你可以忽略所有的warning，因为他并不是一个错误，而更像是一个提醒

感谢您的回复，感谢！

**Comment by Da-ker** [comment]
> 1. 我更倾向于这个是内核在处理内部流量时出现的一些问题，在[内核的仓库](https://github.com/MetaCubeX/mihomo)可以经常看见这种相关的issue
> 2. [svchost.exe](https://zh.wikipedia.org/wiki/Svchost.exe)是Windows里专门用来执行程序dll的前导程序，根据[这篇文章](https://malwaretips.com/blogs/svchost-exe-virus-removal/)所说，svchost.exe可能通常不会直接请求网络，如果你看到了大量的网络请求，可能遇到了文中所说的被恶意软件滥用或者遇到了木马程序，希望我猜的是错的，但是也希望你运行一下杀毒软件检查电脑
> 3. warning的含义无法猜测，根据日志所说，就是朝着一个ip发送了请求，但是或许是i或许是o出现了超时问题，导致超时的可能很多，没有办法从这一条日志分析出来
> 4. 如果不影响正常使用，你可以忽略所有的warning，因为他并不是一个错误，而更像是一个提醒

大佬，您的这篇文章上锁了，一直收藏学习，请问通过什么方式能够获取访问密码呢？

**Comment by lainbo** [comment]
6 个 0

Da-ker ***@***.***>于2024年9月6日 周五22:43写道：
